version: '3.9'

services:
    db:
        image: mysql:8.0
        container_name: databank
        restart: always
        environment:
            MYSQL_DATABASE: databank-fitness-challenge-app
            MYSQL_USER: root
            MYSQL_PASSWORD: password
        ports:
            - '3307:3306'
        volumes:
            - db_data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: always
        environment:
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: rootpass
        ports:
            - '8080:80'

volumes:
    db_data:
